#pragma config(StandardModel, "Clawbot IQ With Sensors")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(1){
		tankControl(JoyY2, JoyY1, 10);
		armControl(motor10, Btn4, Btn1);
		armControl(motor11, Btn2, Btn3);
	}
}
