#pragma config(StandardModel, "Clawbot IQ With Sensors")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
void forwardByCm(float cm)
{
	float r = cm/20;
	forward(r, rotations, 50);
}
task main()
{
	forwardByCm(50);
}
