#pragma config(StandardModel, "Clawbot IQ With Sensors")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

const float cmPerRotation = 19;

void forwardByCm(float cm)
{
	float r = cm/cmPerRotation;
	forward(r, rotations, 50);
}
task main()
{
	forwardByCm(50);
	//forward(1, rotations, 50)
	displayTextLine(1, "cmPerRotation = %f", cmPerRotation);
}
