#pragma config(StandardModel, "Clawbot IQ With Sensors")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	moveMotor(motor10,3,seconds,63);
	moveMotor(motor10,3,seconds,-63);
}
