#pragma config(StandardModel, "Clawbot IQ With Sensors")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	moveMotor(motor11, 1, seconds, 50);
	moveMotor(motor10, 3, seconds, 50);
	forward(3.5, rotations, 75);
	moveMotor(motor10, 3, seconds, -50);
	moveMotor(motor11, 1, seconds, -50);
	backward(3.5, rotations, 75);
}
