#pragma config(StandardModel, "Clawbot IQ With Sensors")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(1){
		setMotorSpeed(motor1, 50);
		setMotorSpeed(motor6, 50);
	}
}
