#pragma config(StandardModel, "Clawbot IQ With Sensors")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void turnRightByGyro(int degrees)
{
	resetGyro(port4);
	while(getGyroDegrees(port4)>-degrees)
	{
		setMotorSpeed(motor1,50);
		setMotorSpeed(motor6,-50);
	}
	setMotorSpeed(motor1,0);
	setMotorSpeed(motor6,0);
}

void turnLeftByGyro(int degrees)
{
	resetGyro(port4);
	while(getGyroDegrees(port4)<degrees)
	{
		setMotorSpeed(motor1,-50);
		setMotorSpeed(motor6,50);
	}
	setMotorSpeed(motor1,0);
	setMotorSpeed(motor6,0);
}
task main()
{
	moveMotor(motor11,1.5,seconds,-50);
	moveMotor(motor10,1.7,seconds,50);

	forward(6.8, rotations, 75);

	moveMotor(motor11,1.5,seconds,50);
	moveMotor(motor10,1.7,seconds,-50);

	turnLeftByGyro(90);

	forward(2, rotations, 75);

	turnLeftByGyro(87);

	moveMotor(motor11,1.5,seconds,-50);
	moveMotor(motor10,1.7,seconds,50);

	forward(7.8, rotations, 75);

	moveMotor(motor11,1.5,seconds,50);
	moveMotor(motor10,1.7,seconds,-50);

	turnLeftByGyro(178);

	forward(2.8, rotations, 75);

	turnLeftByGyro(43.2);

	moveMotor(motor11,1.5,seconds,-50);
	moveMotor(motor10,1.7,seconds,50);

	forward(6.8, rotations, 75);

	moveMotor(motor11,1.5,seconds,50);
	moveMotor(motor10,1.7,seconds,-50);

	turnLeftByGyro(90);

	forward(2.3, rotations, 75);

	turnLeftByGyro(88.3);

	moveMotor(motor11,1.5,seconds,-50);
	moveMotor(motor10,1.7,seconds,50);

	forward(7.8, rotations, 75);

	moveMotor(motor11,1.5,seconds,50);
	moveMotor(motor10,1.7,seconds,-50);

	turnLeftByGyro(180);

	moveMotor(motor11,1.5,seconds,-50);
	moveMotor(motor10,1.7,seconds,50);

	forward(6.8, rotations, 75);

	moveMotor(motor11,1.5,seconds,50);
	moveMotor(motor10,1.7,seconds,-50);

	turnLeftByGyro(88.7);

	forward(2, rotations, 75);

	turnLeftByGyro(85.5);

	moveMotor(motor11,1.5,seconds,-50);
	moveMotor(motor10,1.7,seconds,50);

	forward(1.5, rotations, 75);

	forward(7.8, rotations, 75);

	moveMotor(motor11,1.5,seconds,50);
	moveMotor(motor10,1.7,seconds,-50);
}
