#pragma config(StandardModel, "Clawbot IQ With Sensors")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void forwardByCm(float cm)
{
	const float cmPerRotation = 19;
	float r = cm/cmPerRotation;
	forward(r, rotations, 50);
}

void turnByGyro(int degrees)
{
	int motor1Speed = 50;
	int motor6Speed = -50;
	if (degrees < 0) {
		motor1Speed = -50;
		motor6Speed = 50;
	}
	resetGyro(port4);
	while(abs(getGyroDegrees(port4)) < abs(degrees))
	{
		setMotorSpeed(motor1, motor1Speed);
		setMotorSpeed(motor6, motor6Speed);
	}
	setMotorSpeed(motor1,0);
	setMotorSpeed(motor6,0);
}

void armUp() {
	moveMotor(motor10,3,seconds,63);
}

void armDown() {
	moveMotor(motor10,3,seconds,-63);
}

task main()
{
	forwardByCm(126);

	//armUp();
	turnByGyro(-94.91);
	//armDown();
	forwardByCm(46);

	//armUp();
	turnByGyro(-88.27);
	//armDown();
	forwardByCm(124);

	armUp();
	turnByGyro(180);
	armDown();
	forwardByCm(36);

	//armUp();
	turnByGyro(-40.06);
	//armDown();
	forwardByCm(104);

	//armUp();
	turnByGyro(-87.55);
	//armDown();
	forwardByCm(41);

	armUp();
	turnByGyro(-92.24);
	armDown();
	forwardByCm(120);

	//armUp();
	turnByGyro(91.82);
	//armDown();
	forwardByCm(41);

	armUp();
	turnByGyro(84);
	armDown();
	forwardByCm(110);
}
