#pragma config(StandardModel, "Clawbot IQ With Sensors")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
void right(){
	resetGyro(port4);
	while(getGyroDegrees(port4)>-90){
		displayTextLine(1, "%d",getGyroDegrees(port4));
		setMotorSpeed(motor1,25);
		setMotorSpeed(motor6,-25);
	}
	setMotorSpeed(motor1,0);
	setMotorSpeed(motor6,0);
}

void left()
{
	resetGyro(port4);
	while(getGyroDegrees(port4)<90){
		displayTextLine(1, "%d",getGyroDegrees(port4));
		setMotorSpeed(motor1,-50);
		setMotorSpeed(motor6,50);
	}
	setMotorSpeed(motor1,0);
	setMotorSpeed(motor6,0);
}


task main()
{
	backward(4, rotations, 100);
	forward(4, rotations, 100);
	right();
	forward(4, rotations, 100);
	left();
	forward(3.5, rotations, 100);
	left();
	forward(7.5, rotations, 100);
	right();
	right();
	forward(7.5, rotations, 100);
	right();
	forward(7.5, rotations, 100);
	turnRight(1.1, seconds, 50);
	forward(7.5, rotations, 100);
	right();
	forward(4, rotations, 100);
}
