#pragma config(StandardModel, "Clawbot IQ With Sensors")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
void turnRightByMotor(float degrees)
{
	float rotation = degrees/124*1;
	turnRight(rotation, rotations, 50);
}
task main()
{
	turnRight(2, rotations, 50);
	sleep(1000);
	//turnRightByMotor(90);
}
