#pragma config(StandardModel, "Clawbot IQ With Sensors")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
void turnRightByGyro(int degrees)
{
	resetGyro(port4);
	while(getGyroDegrees(port4)>-degrees + 1)
	{
		setMotorSpeed(motor1,35);
		setMotorSpeed(motor6,-35);
	}
	setMotorSpeed(motor1,0);
	setMotorSpeed(motor6,0);
}

void turnLeftByGyro(int degrees)
{
	resetGyro(port4);
	while(getGyroDegrees(port4)<degrees - 1)
	{
		setMotorSpeed(motor1,-35);
		setMotorSpeed(motor6,35);
	}
	setMotorSpeed(motor1,0);
	setMotorSpeed(motor6,0);
}
task main()
{
	while(1){
		if(getDistanceValue(port7) < 500){
			setMultipleMotors(50, leftmotor, rightMotor);
			while(getDistanceValue(port7) > 100){}
			stopMultipleMotors(leftMotor, rightMotor);
			moveMotor(motor11, 2, seconds, 50);
			moveMotor(motor10, 5, seconds, 50);
			moveMotor(motor11, 2, seconds, -50);
			moveMotor(motor10, 5, seconds, -50);
			forward(1, rotations, 50);
			turnLeftByGyro(90);
		}
		else if(getDistanceValue(port7) > 400){
			forward(5, rotations, 50);
		}
		else if(getDistanceValue(port7) < 600){
			setMultipleMotors(50, leftmotor, rightMotor);
			while(getDistanceValue(port7) > 100){}
			stopMultipleMotors(leftMotor, rightMotor);
			turnRightByGyro(90);
			setMultipleMotors(50, leftmotor, rightMotor);
			while(getDistanceValue(port7) > 720){}
			stopMultipleMotors(leftMotor, rightMotor);
			turnLeftByGyro(90);
			forward(2, rotations, 50);
		}
		else if(getColorName(port3) == 5 && 6){
				stopMultipleMotors(leftMotor, rightMotor);
				while(getColorName(port3) != colorViolet){}
				turnLeftByGyro(90);
				forward(5, rotations, 50);
			}
			else{
				setTouchLEDColor(port2, colorOrange);
				turnLeftByGyro(90);
				setTouchLEDColor(port2, colorOrange);
				forward(5, rotations, 50);
			}
		}

	}
