#pragma config(StandardModel, "Clawbot IQ With Sensors")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main(){
	moveMotor(motor11, 1, seconds, 50);
	forward(1.5, rotations, 50);
	while(getMotorEncoder(leftMotor) < 10 * 360){
		lineTrackLeft(port3);
	}
	resetMotorEncoder(leftMotor);
	while(getMotorEncoder(leftMotor) < 10 * 360){
		lineTrackRight(port3);
	}
}
