#pragma config(StandardModel, "Clawbot IQ With Sensors")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	for(int i = 0; i < 5; i++){
		forward(1, rotations, 50);
		backward(1, rotations, 50);
	}
}
