#pragma config(StandardModel, "Clawbot IQ With Sensors")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(getDistanceValue(port7) > 150){
		setTouchLEDColor(port2, colorGreen);
		forward(1, rotations, 50);
		setTouchLEDColor(port2, colorRed);
		backward(1, rotations, 50);
	}
}
