#pragma config(StandardModel, "Clawbot IQ With Sensors")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(getMotorEncoder(leftMotor) < 1440){
		if(getDistanceValue(port7) < 100){
			stopMultipleMotors(motor1, motor6);
		}
		else{
			setMultipleMotors(50, motor1, motor6);
		}
	}
}
