#pragma config(StandardModel, "Clawbot IQ With Sensors")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	setMultipleMotors(50, leftMotor, rightMotor);
	while(getDistanceValue(port7) > 100){}
	setMultipleMotors(-50, leftMotor, rightMotor);
}
