#pragma config(StandardModel, "Clawbot IQ With Sensors")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void turnRightByGyro(int degrees)
{
	resetGyro(port4);
	while(getGyroDegrees(port4)>-degrees)
	{
		setMotorSpeed(motor1,50);
		setMotorSpeed(motor6,-50);
	}
	setMotorSpeed(motor1,0);
	setMotorSpeed(motor6,0);
}

void turnLeftByGyro(int degrees)
{
	resetGyro(port4);
	while(getGyroDegrees(port4)<degrees)
	{
		setMotorSpeed(motor1,-50);
		setMotorSpeed(motor6,50);
	}
	setMotorSpeed(motor1,0);
	setMotorSpeed(motor6,0);
}

void forwardAndDetection(float rotations ){
	resetMotorEncoder(leftMotor);
	while(getMotorEncoder(leftMotor) < rotations * 360){
		displayTextLine(1, "%f", getMotorEncoder(leftMotor) / 360);
		if(getDistanceValue(port7) < 200){
			stopMultipleMotors(motor1, motor6);
		}
		else{
			setMultipleMotors(50, motor1, motor6);
		}
	}
}
task main()
{
	forwardAndDetection(6.8);

	turnLeftByGyro(90);

	forward(2, rotations, 50);

	turnLeftByGyro(87);

	forwardAndDetection(7.8);

	turnLeftByGyro(175);

	forward(2.8, rotations, 50);

	turnLeftByGyro(45.2);

	forwardAndDetection(6.8);

	turnLeftByGyro(90);

	forward(2.3, rotations, 50);

	turnLeftByGyro(88.3);

	forwardAndDetection(7.8);

	turnLeftByGyro(180);

	forwardAndDetection(6.8);

	turnLeftByGyro(88.7);

	forward(2, rotations, 50);

	turnLeftByGyro(85.5);

	forwardAndDetection(9.3);
}
