#pragma config(StandardModel, "Clawbot IQ With Sensors")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
void turnRightByGyro(int degrees)
{
	resetGyro(port4);
	while(getGyroDegrees(port4) > -degrees)
	{
		setMotorSpeed(motor1,35);
		setMotorSpeed(motor6,-35);
	}
	setMotorSpeed(motor1,0);
	setMotorSpeed(motor6,0);
}
task main()
{
	for(int i = 0; i < 4; i++){
		setTouchLEDColor(port2, colorGreen);
		forward(7.5, rotations, 50);
		setTouchLEDColor(port2, colorYellow);
		turnRightByGyro(90);
	}
}
