#pragma config(StandardModel, "Clawbot IQ With Sensors")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
void turnLeftByGyro(int degrees)
{
	resetGyro(port4);
	while(getGyroDegrees(port4)<degrees - 1)
	{
		setMotorSpeed(motor1,-35);
		setMotorSpeed(motor6,35);
	}
	setMotorSpeed(motor1,0);
	setMotorSpeed(motor6,0);
}
task main()
{
	setTouchLEDColor(port2, colorOrange);
	forward(3, rotations, 50);
	setTouchLEDColor(port2, colorOrange);
	turnLeftByGyro(90);
	setTouchLEDColor(port2, colorOrange);
	forward(5, rotations, 50);
}
