#pragma config(StandardModel, "Clawbot IQ With Sensors")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void turnRightByGyro(int degrees)
{
	resetGyro(port4);
	while(getGyroDegrees(port4)>-degrees +1)
	{
		setMotorSpeed(motor1,20);
		setMotorSpeed(motor6,-20);
	}
	setMotorSpeed(motor1,0);
	setMotorSpeed(motor6,0);
}

void turnLeftByGyro(int degrees)
{
	resetGyro(port4);
	while(getGyroDegrees(port4)<degrees )
	{
		setMotorSpeed(motor1,-20);
		setMotorSpeed(motor6,20);
	}
	setMotorSpeed(motor1,0);
	setMotorSpeed(motor6,0);
}
float step = 0.74 ;
task main()
{
	while(1){
		setTouchLEDColor(port2, colorNone);
		sleep(2000);
		if(getDistanceValue(port7) > 1000){
			forward(step * 4, rotations, 50);
			//go to the center
			if(getColorName(port3) ==colorDarkYellow || getColorName(port3) ==colorYellow){
				//in fire room
				setTouchLEDColor(port2, colorRed);
				while(getColorName(port3) != colorViolet && getColorName(port3) != colorRed){}
			}
			else{
				//in clear room
				setTouchLEDColor(port2, colorOrange);
			}
			turnLeftByGyro(90);
			forward(step * 8.75, rotations, 50);
		}
		else{
			if(getDistanceValue(port7) < 300){
				//in walled room
				setTouchLEDColor(port2, colorBlue);
				turnLeftByGyro(90);
				setMultipleMotors(50, leftmotor, rightMotor);
				while(getDistanceValue(port7) > 100){}
				stopMultipleMotors(leftMotor, rightMotor);
				turnRightByGyro(90);
				forward(3, rotations, 50);
				turnLeftByGyro(90);
				forward(4 * step, rotations, 50);
			}
			else{
				//in rescue room
				moveMotor(motor11, 1, seconds, -50);
				setTouchLEDColor(port2, colorGreen);
				setMultipleMotors(50, leftmotor, rightMotor);
				while(getDistanceValue(port7) > 100){}
				stopMultipleMotors(leftMotor, rightMotor);
				moveMotor(motor11, 2, seconds, 50);
				moveMotor(motor10, 5, seconds, 50);
				moveMotor(motor11, 2, seconds, -50);
				moveMotor(motor10, 5, seconds, -50);
				forward(1, rotations, 50);
				turnLeftByGyro(90);
				forward(8.75 * step, rotations, 50);
			}
		}
	}
}
