#pragma config(StandardModel, "Clawbot IQ With Sensors")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// Program the robot from away from an object/wall, then stops when it's far enough!
// Make sure the robot has the Ultrasonic Sensor, then place the robot up close to a object/wall.
// Next, program the robot to start moving away from the wall. When the robot is greater than 300mm,
// it should stop.

task main()
{
	setMultipleMotors(50, leftMotor, rightMotor);
	while(getDistanceValue(port7) < 300){
	}
	stopAllMotors();
}
