#pragma config(StandardModel, "Clawbot IQ With Sensors")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// Use getDistanceValue

task main()
{
	setMultipleMotors(-50, leftMotor, rightMotor);
	while(getDistanceValue(port7) > 500){
	}
	stopAllMotors();
}
