#pragma config(StandardModel, "Clawbot IQ With Sensors")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// Use getColorName

task main()
{
	setMultipleMotors(50, motor1, motor6);
	while(getColorName(port3) != colorRed){
	}
	stopMultipleMotors(motor1, motor6);
}
