#pragma config(StandardModel, "Clawbot IQ With Sensors")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// Use setMultipleMotors and getBumperValue
task main()
{
	moveMotor(motor10,5,seconds,50);
	setMultipleMotors(50, leftMotor, rightMotor);
	while(getBumperValue(port8) == 0){
	}
	stopAllMotors();
}
