#pragma config(StandardModel, "Clawbot IQ With Sensors")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// Use setMultipleMotors and getBumperValue
task main()
{
	setMultipleMotors(10000, motor1, motor6);
	while(getBumperValue(port8) == 0){
	}
	stopAllMotors();
}
