#pragma config(StandardModel, "Clawbot IQ With Sensors")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// Make sure the robot has the Color Sensor, then place it at a distance from a red object.
// Next, program the robot to move forward, continuously. The robot should only stop when
// the Color Sensor detects that red object.
// Note: Having the Color Sensor face downwards until it detects a red surface works just as fine.

task main()
{
	setMultipleMotors(50, motor1, motor6);
	while(getColorName(port3) != colorRed){
	}
	stopMultipleMotors(motor1, motor6);
	while(getColorName(port3) == colorRed){
	}
	forward(1, rotations, 50);
}
