#pragma config(StandardModel, "Clawbot IQ With Sensors")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// Program the robot to activate different colors of the Touch LED as it moves closer to an object!
// Make sure the robot has Touch LED and the Ultrasonic Sensor, then place the robot a lengthy
// distance away from a object/wall.

// Program the robot so that the Touch LED turns on to the color yellow, then moves forward,
// closer to the object/wall. As it moves closer, the Touch LED should change colors.
// The robot should then stop when it gets less than 250mm away from the object/wall.

// The Touch LED should change to the following colors at these distances:
// Yellow (Yellow) if distance is greater than 750mm
// Orange (Orange) if distance is less than 750mm
// Red (Red) if distance is less than 500mm
// The robot should stop if distance is less than 250mm (virtual world instruction says 100mm)

task main()
{
	setMultipleMotors(-100, leftMotor, rightMotor);
	setTouchLEDColor(port2, colorYellow);
	while(getDistanceValue(port7) > 750){
	}
	setTouchLEDColor(port2, colorOrange);
	while(getDistanceValue(port7) > 500){
	}
	setTouchLEDColor(port2, colorRed);
	while(getDistanceValue(port7) > 250){
	}
	stopAllMotors();
}
