#pragma config(StandardModel, "Clawbot IQ With Sensors")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(1){
		setMultipleMotors(50, motor1, motor6);
		setTouchLEDColor(port2, colorGreen);
		while(getColorName(port3) != colorRed){
		}
		stopMultipleMotors(motor1, motor6);
		setTouchLEDColor(port2, colorRed);
		while(getColorName(port3) == colorRed){
		}
	}
}
