
// turn as accurate as you can

#pragma config(StandardModel, "Clawbot IQ With Sensors")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
task main()
{
	resetGyro(port4);
	setMotorSpeed(motor1, -35);
	setMotorSpeed(motor6, 35);
	while(getGyroDegrees(port4) < 89){
	}
	stopMultipleMotors(motor1, motor6);
}
