
// Use resetGyro and getGyroDegrees

#pragma config(StandardModel, "Clawbot IQ With Sensors")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
task main()
{
	resetGyro(port4);
	setMotorSpeed(motor1, -50);
	setMotorSpeed(motor6, 50);
	while(getGyroDegrees(port4) < 90){
	}
	stopMultipleMotors(motor1, motor6);
}
