#pragma config(StandardModel, "Clawbot IQ With Sensors")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// Using a Touch Sensor, program the robot to touch all four walls of a room!
// Using a 4'x4 table (with walls), have the robot start near the middle facing straight
// to a wall. Using a touch sensor, program the robot to move forward and touch ALL four walls.
// Note: The touch sensor is under the robot's arm, and does not need to reset to the center
// after each wall.


void turnRightByGyro(int degrees)
{
	resetGyro(port4);
	while(getGyroDegrees(port4)>-degrees)
	{
		setMotorSpeed(motor1,50);
		setMotorSpeed(motor6,-50);
	}
	setMotorSpeed(motor1,0);
	setMotorSpeed(motor6,0);
}

void turnLeftByGyro(int degrees)
{
	resetGyro(port4);
	while(getGyroDegrees(port4)<degrees)
	{
		setMotorSpeed(motor1,-50);
		setMotorSpeed(motor6,50);
	}
	setMotorSpeed(motor1,0);
	setMotorSpeed(motor6,0);
}
task main()
{
	for( int i = 0; i < 4 ; i++){
		setMultipleMotors(50, leftMotor, rightMotor);
		while(getBumperValue(port8) == 0){
		}
		backward(2, rotations, 50);
		turnRightByGyro(90);
	}
}
